//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCatedraPED_SistemaInventario.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ofertas
    {
        public int ID_Oferta { get; set; }
        public int ID_Producto { get; set; }
        public int PorcentajeDescuento { get; set; }
        public string Descripcion { get; set; }
        public int Prioridad { get; set; }
        public bool Activa { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
