//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCatedraPED_SistemaInventario.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CatalogoProductos
    {
        public int ID_Producto { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Categoria { get; set; }
        public decimal PrecioOriginal { get; set; }
        public Nullable<int> PorcentajeDescuento { get; set; }
        public Nullable<decimal> PrecioFinal { get; set; }
        public string OfertaDescripcion { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public int Stock { get; set; }
        public string RutaImagen { get; set; }
    }
}
